### ISSUE TITLE
Doesn't run in Chrome (MIME type error)

### ISSUE THREAD

**Issue by TheWrongAlice** [phrase/react-i18next-phraseapp-demo#1]
I did `npm install` and `node app.js`. Got this error: 
<img width="927" alt="screenshot 2018-07-09 15 10 13" src="https://user-images.githubusercontent.com/7847509/42452416-3745e4c4-838a-11e8-9377-f793654d9aae.png">

**Comment by theSoenke** [comment]
Thanks for reporting this. I will have a closer look at this

**Comment by theSoenke** [comment]
Could run try to run `npm run build` for `node app.js`? It looks like the bundle.js has not been build yet. I will definitely add this to the documentation

**Comment by theSoenke** [comment]
Now it should be possible to run `npm start` and everything should work correctly. Please let me know if that is not the case for you
