### ISSUE TITLE
error while searching for strings

### ISSUE THREAD

**Issue by bigfish** [phrase/react-i18next-phraseapp-demo#3]
![screen shot 2018-09-12 at 12 33 53 pm](https://user-images.githubusercontent.com/34862/45439585-33765280-b688-11e8-81cd-39431ed26c61.png)

I'm seeing a 404 error in debug console when trying to search for a string...and also no results.

Perhaps the app needs updating?

**Comment by theSoenke** [comment]
I have been trying to reproduce this but was not successful so far. Could you maybe check whether the project id is correct?

**Comment by theSoenke** [comment]
You found a bit of  a workaround here :) Actually, you normally have to only replace the `projectId` in the index.html file of the project and then log in with your credentials
